# Node.js Express Web App on Linux
# Build a Node.js Express app and deploy it as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'vs2017-win2016'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm build
      displayName: 'npm install and build'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
          rootFolderOrFile: '{{ pipelineParameters.workingDirectory }}'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

- stage: Release
  jobs:
  - job: ReleaseJob
    pool:
      vmImage: 'vs2017-win2016'

    steps:
    - task: AzureWebApp@1
      displayName: 'Azure Web App Deploy'
      inputs:
        azureSubscription: '{{ targetResource.serviceConnectionId }}'
        appType: webApp
        appName: '{{ targetResource.resource.name }}'
        package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
